server:
  port: 18086
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: search
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 10.211.55.3:9300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#超时配置
ribbon:
  ReadTimeout: 300000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
